# -*- coding: utf-8 -*-
"""max_drawdown_historgram_of_aapl_over_last_5yrs.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13RnewOU59lp1skdfm_6ooVwWgOG4IngP
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import yfinance as yf

# Step 1: Download historical stock price data for AAPL
ticker = 'GOOGL'
data = yf.download(ticker, period='5y', interval='1d')

# Step 2: Calculate the drawdown
data['Peak'] = data['Adj Close'].cummax()  # Calculate the running max
data['Drawdown'] = (data['Adj Close'] - data['Peak']) / data['Peak']  # Drawdown in percentage terms

# Step 3: Find the max drawdown for each period (rolling max)
max_drawdown = data['Drawdown'].min()  # Maximum drawdown over the whole period

# Step 4: Plot a histogram of drawdowns
plt.figure(figsize=(10, 6))
plt.hist(data['Drawdown'].dropna(), bins=50, color='blue', alpha=0.7)
plt.title(f'Max Drawdown Histogram of {ticker} Over the Last 5 Years')
plt.xlabel('Drawdown (%)')
plt.ylabel('Frequency')
plt.grid(True)
plt.show()
